version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    command: mongod --dbpath /data/db --bind_ip mongo,localhost
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ${PWD}/data/mongo:/data/db

  minic-server:
    build:
      dockerfile: Dockerfile.server
    image: minic-server
    deploy:
      replicas: 1
    depends_on:
      - rabbitmq
    expose:
      - 23450
    environment:
      - MONGO_HOST=mongo
      - RABBITMQ_HOST=rabbitmq
      - ENFORCE_EMAIL_VERIFICATION=False
    
  minic-webclient:
    build:
      dockerfile: Dockerfile.webclient
    image: minic-webclient
    deploy:
      replicas: 1
    expose:
      - 23451
    environment:
      - MINIC_SERVER_HOST=nginx
      - MINIC_SERVER_PORT=33450
  
  minic-email-server:
    build:
      dockerfile: Dockerfile.email-server
    image: minic-email-server
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1
    expose:
      - 23452
    environment:
      - MONGO_HOST=mongo
      - RABBITMQ_HOST=rabbitmq
      - GMAIL_USERNAME=username
      - GMAIL_PASSWORD=password
      - EMAIL_SERVER_PORT=33452
      - EMAIL_SERVER_HOST=localhost

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minic-server
      - minic-webclient
    ports:
      - 33450:33450
      - 33451:33451
      - 33452:33452

  rabbitmq:
    image: rabbitmq:3.9.11-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672