FROM node:16.13.0-alpine3.12

COPY minic_webclient /home/minic_webclient

RUN cd /home/minic_webclient && \
    npm install && \
    cd client && \
    npm install

RUN cd /home/minic_webclient && \
    npm run build

CMD node /home/minic_webclient/build/server.js