kind: Service
apiVersion: v1
metadata:
  name: minic-webclient
  labels:
    app: minic-webclient
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 23451
  selector:
    app: minic-webclient